"""
Shared Memory
acts as a common storage for all the agents
Responsibilities:
1. Store information generated by agents 
2. Retrieve information for downstream agents
3. Provide a common communication mechanism 
4. Remain independent of anu specific AI Agent
"""

from typing import Any

class SharedMemory:
    """
    Share memory accessible 
    """

    def __init__(self):
        self._memory: dict[str, Any] = {}

    def add(self, key:str, value:Any)->None:
        """
        Store data
        """

        self._memory[key] = value


    def get(self, key:str)->str:
        """
        Retrieve data
        """

        return self._memory.get(key)

    def exists(self, key:str)->bool:
        """
        Check if the key exists
        """

        return key in self._memory


    def remove(self, key:str) -> None:
        """
        Remove specific key from memory 
        Arg: 
            key: Memory key
        """
        self._memory.pop(key, None)


    def clear(self, key:str)->bool:
        """
        Clear memory
        """

        self._memory.clear()

    def get_all(self) -> dict[str, Any]:
        """
        Return the complete memory
        Returns:
            Dictionary containing all stored values
        """
        return self._memory

    def display(self, key:str)->bool:
        """
        Print current memory
        """

        print("="*50)
        print("SHARED MEMORY ")
        print("="*50)

        for key, value in self._memory.items():
            print(f"{key}")
            print(value)
            print("="*50)